# Generated by Django 2.0.3 on 2018-11-08 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('apelido', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desafiado', models.CharField(max_length=30)),
                ('desafiante', models.CharField(max_length=30)),
                ('data', models.DateTimeField(verbose_name='data')),
                ('hora', models.DateTimeField(verbose_name='hora')),
                ('games_1set_desafiado', models.IntegerField(default=0)),
                ('games_1set_desafiante', models.IntegerField(default=0)),
                ('games_2set_desafiado', models.IntegerField(default=0)),
                ('games_2set_desafiante', models.IntegerField(default=0)),
                ('games_3set_desafiado', models.IntegerField(default=0)),
                ('games_3set_desafiante', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rodada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('ano', models.DateTimeField(verbose_name='ano da rodada')),
            ],
        ),
        migrations.AddField(
            model_name='jogo',
            name='rodada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenis.Rodada'),
        ),
    ]
