# Generated by Django 2.0.3 on 2018-11-08 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenis', '0002_auto_20181108_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='hora',
        ),
    ]
