# Generated by Django 2.0.3 on 2018-11-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenis', '0004_auto_20181114_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='correio_eletronico',
            field=models.CharField(max_length=50),
        ),
    ]
